### ISSUE TITLE
Weakly typed dependencies?

### ISSUE THREAD

**Issue by Sxtanna** [VoxelGamesLib/VoxelGamesLibv2#107]
Are the class arrays at 

[Feature#getDependencies](https://github.com/VoxelGamesLib/VoxelGamesLibv2/blob/master/src/main/java/com/voxelgameslib/voxelgameslib/feature/Feature.java#L45)
and
[Feature#getSoftDependencies](https://github.com/VoxelGamesLib/VoxelGamesLibv2/blob/master/src/main/java/com/voxelgameslib/voxelgameslib/feature/Feature.java#L54)

meant to be weakly typed? 

And if so, can they not be?

**Comment by MiniDigger** [comment]
I think they did use generics at one point (git blame doesn't show it, :shrug:), but it caused issues (generics suck). if you are able to make it strongly typed to Feature again, go ahead.

**Comment by Sxtanna** [comment]
Any reason its an Array and not like... a List?

**Comment by Sxtanna** [comment]
Would be way nicer to work with.

**Comment by MiniDigger** [comment]
some parts of this were written in 2014 where java didn't have nice ways to create lists in one line, thats why its an array. since we can use Arrays.asList in java now, its ok to change it to a list. maybe you should let me make this change tho since I have a workspace with all gamemodes, it would make refactoring easier.

**Comment by Sxtanna** [comment]
Ok. I'll go touch some other stuff then 😈

**Comment by MiniDigger** [comment]
this was fixed
